### PR TITLE
DO_NOT_MERGE: roles/rhsm: Replace subscription-manager commands with redhat_subscription

### PR DESCRIPTION
**Pull request by pablomh**

### CODE REVIEW

**Comment by pablomh** [comment]
I'll try to replace all instances and not only a few, so stay tuned.

**Comment by jhutar** [comment]
Hello. Please check this:

https://github.com/jhutar/ansible-role-rhsm_helper

I have used it here:

https://github.com/redhat-performance/satperf/blob/master/playbooks/satellite/installation_v2.yaml#L13

I'm now testing this on RHEL8 local VMs, but would like to test on RHEL7 as well and make it default.

**Comment by jhutar** [comment]
Hello @pablomh . I think this can be closed now as we are using redhat_subscription in the background now.

**Comment by pablomh** [comment]
No, I've been using your new code and everything has been fine :)

**Pull request closed without merging**
